INSERT INTO category (id, name) VALUES (1, 'Outdoor Cafes');
INSERT INTO category (id, name) VALUES (2, 'Vegan Pet-Friendly Restaurants');
INSERT INTO category (id, name) VALUES (3, 'Dog Parks with Dining Areas');
INSERT INTO category (id, name) VALUES (4, 'Rooftop Restaurants for Pets');
INSERT INTO category (id, name) VALUES (5, 'Pet-Friendly Breweries');
INSERT INTO category (id, name) VALUES (6, 'Small Pet Accommodation Restaurants');
INSERT INTO category (id, name) VALUES (7, 'Pet-Themed Cafes');
INSERT INTO category (id, name) VALUES (8, 'Waterfront Pet-Friendly Restaurants');
INSERT INTO category (id, name) VALUES (9, 'Restaurants with Pet Play Zones');
INSERT INTO category (id, name) VALUES (10, 'Casual Dining for Pets and Owners');